name: Auto Deploy
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: fnkr/github-action-git-bash@v1 
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy
